'use client';

import { useEffect, useMemo } from 'react';
import { AppNav } from '@/components/app-nav';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Printer, ArrowLeft, FileText } from 'lucide-react';
import Link from 'next/link';
import { getTodayOrders } from '@/lib/pos/storage';
import type { OrderRecord, PaymentMethod } from '@/lib/pos/types';
import { formatPrice, formatDate } from '@/lib/pos/format';
import { useState } from 'react';

function printEodReport(
  orders: OrderRecord[],
  storeName: string,
  date: string
) {
  const revenue = orders.reduce((s, o) => s + o.total, 0);
  const tax = orders.reduce((s, o) => s + o.taxAmount, 0);
  const discounts = orders.reduce((s, o) => s + o.discountAmount, 0);
  const methods: Record<PaymentMethod, number> = { cash: 0, gcash: 0, card: 0 };
  orders.forEach((o) => { methods[o.paymentMethod] += o.total; });

  const lines = [
    'END OF DAY REPORT',
    storeName,
    date,
    '═'.repeat(36),
    `Total Orders:     ${orders.length}`,
    `Gross Revenue:    ${formatPrice(revenue + discounts)}`,
    `Discounts:       -${formatPrice(discounts)}`,
    `Tax (12% VAT):    ${formatPrice(tax)}`,
    `Net Revenue:      ${formatPrice(revenue)}`,
    '─'.repeat(36),
    'PAYMENT BREAKDOWN',
    `Cash:             ${formatPrice(methods.cash)}`,
    `GCash:            ${formatPrice(methods.gcash)}`,
    `Card:             ${formatPrice(methods.card)}`,
    '─'.repeat(36),
    'ORDER SUMMARY',
    ...orders.map((o) =>
      `#${o.orderNumber}  ${formatPrice(o.total)}  ${o.paymentMethod.toUpperCase()}`
    ),
    '═'.repeat(36),
    'Generated by CaféPOS',
  ];

  const html = `
    <!DOCTYPE html>
    <html><head><title>EOD Report</title>
    <style>body{font-family:'Courier New',monospace;font-size:12px;max-width:320px;margin:20px auto}pre{white-space:pre-wrap;line-height:1.5}@media print{body{margin:0}}</style>
    </head><body><pre>${lines.join('\n')}</pre><script>window.onload=()=>window.print()</script></body></html>
  `;
  const win = window.open('', '_blank', 'width=360,height=700');
  if (win) { win.document.write(html); win.document.close(); }
}

export default function EodReportPage() {
  const [orders, setOrders] = useState<OrderRecord[]>([]);
  const [storeName, setStoreName] = useState('CaféPOS');
  const today = new Date().toISOString();

  useEffect(() => {
    setOrders(getTodayOrders());
    const stored = localStorage.getItem('cafepos_store_name');
    if (stored) setStoreName(stored);
  }, []);

  const stats = useMemo(() => {
    const revenue = orders.reduce((s, o) => s + o.total, 0);
    const tax = orders.reduce((s, o) => s + o.taxAmount, 0);
    const discounts = orders.reduce((s, o) => s + o.discountAmount, 0);
    const items = orders.reduce((s, o) => s + o.items.reduce((a, i) => a + i.qty, 0), 0);
    return { revenue, tax, discounts, items, count: orders.length };
  }, [orders]);

  const methods = useMemo(() => {
    const m: Record<PaymentMethod, number> = { cash: 0, gcash: 0, card: 0 };
    orders.forEach((o) => { m[o.paymentMethod] += o.total; });
    return m;
  }, [orders]);

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950">
      <AppNav />

      <main className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-6 space-y-5">
        <div className="flex items-center justify-between">
          <div>
            <Link href="/reports" className="inline-flex items-center gap-1 text-xs text-slate-400 hover:text-amber-600 mb-2">
              <ArrowLeft className="w-3 h-3" /> Back to reports
            </Link>
            <h1 className="text-2xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <FileText className="w-6 h-6 text-amber-700" />
              End of Day Report
            </h1>
            <p className="text-sm text-slate-500 mt-1">{formatDate(today)}</p>
          </div>
          <Button
            onClick={() => printEodReport(orders, storeName, formatDate(today))}
            className="bg-amber-700 hover:bg-amber-800 text-white rounded-xl"
          >
            <Printer className="w-4 h-4 mr-2" />
            Print report
          </Button>
        </div>

        <Card className="p-6 bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-700/60 rounded-2xl shadow-none space-y-6">
          <div className="text-center border-b border-slate-100 dark:border-slate-800 pb-4">
            <h2 className="text-lg font-bold text-slate-900 dark:text-white">{storeName}</h2>
            <p className="text-sm text-slate-500">End of Day Summary</p>
            <p className="text-xs text-slate-400 mt-1">{formatDate(today)}</p>
          </div>

          <div className="grid grid-cols-2 gap-4">
            {[
              { label: 'Total orders', value: String(stats.count) },
              { label: 'Items sold', value: String(stats.items) },
              { label: 'Gross revenue', value: formatPrice(stats.revenue + stats.discounts) },
              { label: 'Net revenue', value: formatPrice(stats.revenue) },
              { label: 'Discounts', value: `-${formatPrice(stats.discounts)}` },
              { label: 'Tax (12% VAT)', value: formatPrice(stats.tax) },
            ].map((s) => (
              <div key={s.label} className="p-3 rounded-xl bg-slate-50 dark:bg-slate-800">
                <p className="text-xs text-slate-500">{s.label}</p>
                <p className="text-lg font-semibold text-slate-900 dark:text-white">{s.value}</p>
              </div>
            ))}
          </div>

          <div>
            <h3 className="text-sm font-semibold text-slate-900 dark:text-white mb-3">Payment breakdown</h3>
            <div className="space-y-2">
              {(['cash', 'gcash', 'card'] as PaymentMethod[]).map((m) => (
                <div key={m} className="flex justify-between text-sm">
                  <span className="text-slate-500 capitalize">{m}</span>
                  <span className="font-semibold text-slate-900 dark:text-white">{formatPrice(methods[m])}</span>
                </div>
              ))}
            </div>
          </div>

          <div>
            <h3 className="text-sm font-semibold text-slate-900 dark:text-white mb-3">Order log</h3>
            {orders.length > 0 ? (
              <div className="space-y-1 max-h-64 overflow-y-auto">
                {orders.map((o) => (
                  <div key={o.id} className="flex justify-between text-sm py-1.5 border-b border-slate-50 dark:border-slate-800 last:border-0">
                    <span className="text-slate-600 dark:text-slate-400">
                      #{o.orderNumber} · {o.items.map((i) => `${i.qty}x ${i.name}`).join(', ')}
                    </span>
                    <span className="font-medium text-slate-900 dark:text-white">{formatPrice(o.total)}</span>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-sm text-slate-400 text-center py-8">No orders recorded today</p>
            )}
          </div>
        </Card>
      </main>
    </div>
  );
}
